### ISSUE TITLE
Automate Deployment

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord/obs-web#3]
The resources provided by this repo need to be automatically deployed to a CDN location where they can be accessed.

This should probably be a Github Action and deployment could be to Netlify or to cdn.door43.org (s3 bucket).

Note, part of this would likely be to update where the resources are loaded from in SquareSpace, they are currently loading from a non-optimal location.

**Comment by richmahn** [comment]
Just for reference, the JS & CSS resources are now built and served from http://obs-web.netlify.app/ and is built whenever a commit is made to the `develop` branch (managed through netlify.app as it watches the repo for changes).
